### ISSUE TITLE
Docusaurus version of this repo

### ISSUE THREAD

**Issue by tanishqr-ck** [WebXDAO/blockchain-dev-path#37]
### Detailed description

I would like to suggest to make docusaurus version of this repo. 

### Context

It would be good to read this in doc version for readability.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
@vinzvinci, @shuklaritvik06, @KukretiShubham, @mkubdev, thoughts?

**Comment by mkubdev** [comment]
@tanishqr-ck This is cool idea! 🔥

**Comment by shuklaritvik06** [comment]
> @tanishqr-ck This is really a great idea! fire Do you want us to open a repos ?

Hmm 🤔 maybe for now he can push to a non main branch and after we can have that in other repo and deploy to devpath.webxdao.xyz

**Comment by vinzvinci** [comment]
Hmm is is not good to do it in this repo?

**Comment by shuklaritvik06** [comment]
yes here only haha 😅

**Comment by vinzvinci** [comment]
Closing this issue now. Thanks for your contributions 🎉
