### ISSUE TITLE
[OTHER] Add a license to the repository

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/blockchain-dev-path#43]
### What would you like to share?

We should add a license to this repository. This way, people will know what and what not they can do with this repository, permissions, notices, etc.. I suggest adding the [**MIT license**](https://mit-license.org).

### Additional information

This _could_ be some sort of issue due to that we're pretty much just linking other resources. But still, I think we should still add a license either way. MIT license is the most permissive one, IMO.

### Would you like to work on this issue?

- [X] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shuklaritvik06** [comment]
@vinzvinci  opinion?
