### ISSUE TITLE
[BUG] Polygon link refers to Odyssey DAO

### ISSUE THREAD

**Issue by nirban256** [WebXDAO/blockchain-dev-path#50]
### Description of the bug

On the polygon academy page in the first line the link that is named as ``` Polygon ``` directs to the website of Odyssey DAO which is already being done by the ``` Odyssey DAO ``` page.

I need to know on which website it should direct to?
Can I work on this issue ?

### Please add screenshots (if applicable)

![Screenshot (30)](https://user-images.githubusercontent.com/74231771/196499434-4502142f-7a5f-4d83-9f68-bf680b3e2ef7.png)
![Screenshot (29)](https://user-images.githubusercontent.com/74231771/196499452-501def99-e9e2-45e4-8985-59b170fe1515.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Well spotted @nirban256 !

Polygon should redirect to https://academy.polygon.technology

And maybe you can create an OdysseDAO chapter?
I assign you. 👍🏻

**Comment by nirban256** [comment]
Thank You @mkubdev 
I will first correct this link issue and then later I can contribute to create an OdysseyDAO chapter.
